name: SammuelChan
favicon: null
layout_spectrum: 0.71884
typography_spectrum: 0.73866
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010000'
    - '#ffffff'
    - '#3b4d75'
    - '#b48b7a'
    - '#fea41a'
  brandStrength: 0.5049412352964282
  lightness: 0.0625
  saturation: 0.25041127926670015
  rhythmicContrast: 0.75
purpose: []
